### ISSUE TITLE
Local tests fail with a more recent ruby stack

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/openstreetmap-license-change#5]
```
$ ruby test.rb
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  test.rb:4:in `<main>'
openstreetmap-license-change/test_abbrev.rb:21: warning: key "NE Foobar Crescent" is duplicated and overwritten on line 22
openstreetmap-license-change/test_abbrev.rb:63: warning: key "Westminster st" is duplicated and overwritten on line 71
openstreetmap-license-change/test_abbrev.rb:64: warning: key "Camp east York" is duplicated and overwritten on line 72
openstreetmap-license-change/test_abbrev.rb:65: warning: key "Doctor Feelgood" is duplicated and overwritten on line 73
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_abbrev.rb:13:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_auto.rb:12:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_exceptions.rb:11:in `<top (required)>'
openstreetmap-license-change/test_node.rb:336: warning: key "sugar" is duplicated and overwritten on line 336
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_node.rb:12:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_odbl_tag.rb:11:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_references.rb:11:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_relation.rb:11:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_tags_lowlevel.rb:4:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_tags.rb:12:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_util.rb:11:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_way.rb:11:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_geom.rb:11:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_needs_clarity.rb:22:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_auto_fail.rb:12:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From openstreetmap-license-change/test_diff.rb:4:in `<top (required)>'
test.rb:22:in `<main>': undefined method `run' for #<Minitest::Unit:0x000055748ebe9080> (NoMethodError
```

**Comment by zerebubuth** [comment]
I fixed the warnings/errors in #6, and the test output is now:

```
Run options: --seed 2581

# Running:

.............................................................................................................................................................................................................................................................F...........................................F......

Finished in 1.808631s, 168.0830 runs/s, 4345.2764 assertions/s.

  1) Failure:
TestNeedsClarity#test_way_name_swap [/home/matt/Programming/OSM/openstreetmap-license-change/test_needs_clarity.rb:38]:
--- expected
+++ actual
@@ -1 +1 @@
-[Edit[obj=#<OSM::Way:0xXXXXXX @nodes=[1, 2, 3], @element_id=1, @changeset_id=-1, @timestamp=nil, @visible=true, @version=3, @uid=nil, @tags={"highway"=>"residental"}>], Redact[klass=OSM::Way,element_id=1,version=2,mode=:hidden], Redact[klass=OSM::Way,element_id=1,version=3,mode=:visible]]
+[Redact[klass=OSM::Way,element_id=1,version=2,mode=:hidden]]


  2) Failure:
TestWay#test_way_reversed_by_decliner [/home/matt/Programming/OSM/openstreetmap-license-change/test_way.rb:211]:
--- expected
+++ actual
@@ -1 +1 @@
-[Edit[obj=#<OSM::Way:0xXXXXXX @nodes=[1, 2, 3], @element_id=1, @changeset_id=-1, @timestamp=nil, @visible=true, @version=3, @uid=nil, @tags={"oneway"=>"-1"}>], Redact[klass=OSM::Way,element_id=1,version=2,mode=:hidden], Redact[klass=OSM::Way,element_id=1,version=3,mode=:visible]]
+[Edit[obj=#<OSM::Way:0xXXXXXX @nodes=[3, 1, 2], @element_id=1, @changeset_id=-1, @timestamp=nil, @visible=true, @version=3, @uid=nil, @tags={"oneway"=>"-1"}>], Redact[klass=OSM::Way,element_id=1,version=2,mode=:hidden], Redact[klass=OSM::Way,element_id=1,version=3,mode=:visible]]


304 runs, 7859 assertions, 2 failures, 0 errors, 0 skips
```

I had a look at those two failures, and they seem to be "real" failures, in that they've not been trivially broken and would appear to need some new/extra code to fix.
